In [1]:
import numpy as np
import pandas as pd
from scipy.spatial.distance import cdist
import time

In [2]:
def read_small():
    data_path = 'ml-latest-small/'
    movies = pd.read_csv(data_path + 'movies.csv')
    ratings = pd.read_csv(data_path + 'ratings.csv')
    min_rate = .5
    return movies, ratings, .5

def read_10M():
    data_path = 'ml-10M100K/'
    movies = pd.read_csv(data_path + 'movies.dat', delimiter='::', engine='python')
    ratings = pd.read_csv(data_path + 'ratings.dat', delimiter='::', engine='python')
    min_rate = .5
    return movies, ratings, .5

def read_1M():
    data_path = 'ml-1m/'
    movies = pd.read_csv(data_path + 'movies.dat', delimiter='::', engine='python')
    ratings = pd.read_csv(data_path + 'ratings.dat', delimiter='::', engine='python') 
    min_rate = 1.
    return movies, ratings, 1.

In [3]:
movies, ratings, min_rate = read_10M()

In [4]:
movies

movieId                                              title  \
0            1                                   Toy Story (1995)   
1            2                                     Jumanji (1995)   
2            3                            Grumpier Old Men (1995)   
3            4                           Waiting to Exhale (1995)   
4            5                 Father of the Bride Part II (1995)   
5            6                                        Heat (1995)   
6            7                                     Sabrina (1995)   
7            8                                Tom and Huck (1995)   
8            9                                Sudden Death (1995)   
9           10                                   GoldenEye (1995)   
10          11                     American President, The (1995)   
11          12                 Dracula: Dead and Loving It (1995)   
12          13                                       Balto (1995)   
13          14                                       Nixon (1995)   
14          15                            Cutthroat Island (1995)   
15          16                                      Casino (1995)   
16          17                       Sense and Sensibility (1995)   
17          18                                  Four Rooms (1995)   
18          19              Ace Ventura: When Nature Calls (1995)   
19          20                                 Money Train (1995)   
20          21                                  Get Shorty (1995)   
21          22                                     Copycat (1995)   
22          23                                   Assassins (1995)   
23          24                                      Powder (1995)   
24          25                           Leaving Las Vegas (1995)   
25          26                                     Othello (1995)   
26          27                                Now and Then (1995)   
27          28                                  Persuasion (1995)   
28          29  City of Lost Children, The (Cité des enfants p...   
29          30  Shanghai Triad (Yao a yao yao dao waipo qiao) ...   
...        ...                                                ...   
10651    64906    Battle of Britain, The (Why We Fight, 4) (1943)   
10652    64918               Small Cuts (Petites coupures) (2003)   
10653    64921                              Arabian Nights (1942)   
10654    64923                              Blackbird, The (1926)   
10655    64926     Battle of Russia, The (Why We Fight, 5) (1943)   
10656    64930                       More the Merrier, The (1943)   
10657    64942           Tuya's Marriage (Tuya de hun shi) (2006)   
10658    64944                          Face of a Fugitive (1959)   
10659    64953         Dirty Dozen, The: The Fatal Mission (1988)   
10660    64957        Curious Case of Benjamin Button, The (2008)   
10661    64959        Divide and Conquer (Why We Fight, 3) (1943)   
10662    64969                                     Yes Man (2008)   
10663    64976                                       Hexed (1993)   
10664    64983                                    Valkyrie (2008)   
10665    64986                            Birds of America (2008)   
10666    64990              Pete Seeger: The Power of Song (2007)   
10667    64993  5 Centimeters per Second (Byôsoku 5 senchimêto...   
10668    64997                           War of the Worlds (2005)   
10669    64999          War of the Worlds 2: The Next Wave (2008)   
10670    65001                         Constantine's Sword (2007)   
10671    65006                                     Impulse (2008)   
10672    65011                              Zona Zamfirova (2002)   
10673    65025                             Double Dynamite (1951)   
10674    65027                             Death Kiss, The (1933)   
10675    65037                                       Ben X (2007)   
10676    65088                             Bedtime Stories (2008)   
10677

In [5]:
ratings

userId  movieId  rating  timestamp
0              1      122     5.0  838985046
1              1      185     5.0  838983525
2              1      231     5.0  838983392
3              1      292     5.0  838983421
4              1      316     5.0  838983392
5              1      329     5.0  838983392
6              1      355     5.0  838984474
7              1      356     5.0  838983653
8              1      362     5.0  838984885
9              1      364     5.0  838983707
10             1      370     5.0  838984596
11             1      377     5.0  838983834
12             1      420     5.0  838983834
13             1      466     5.0  838984679
14             1      480     5.0  838983653
15             1      520     5.0  838984679
16             1      539     5.0  838984068
17             1      586     5.0  838984068
18             1      588     5.0  838983339
19             1      589     5.0  838983778
20             1      594     5.0  838984679
21             1      616     5.0  838984941
22             2      110     5.0  868245777
23             2      151     3.0  868246450
24             2      260     5.0  868244562
25             2      376     3.0  868245920
26             2      539     3.0  868246262
27             2      590     5.0  868245608
28             2      648     2.0  868244699
29             2      719     3.0  868246191
...          ...      ...     ...        ...
10000024   71567     1396     3.0  912580688
10000025   71567     1407     2.0  912578457
10000026   71567     1527     5.0  912580647
10000027   71567     1580     3.0  912580688
10000028   71567     1584     3.0  912580647
10000029   71567     1598     2.0  912649143
10000030   71567     1690     3.0  912578406
10000031   71567     1717     1.0  912578457
10000032   71567     1721     4.0  912649271
10000033   71567     1748     3.0  912580647
10000034   71567     1769     3.0  912649037
10000035   71567     1792     2.0  912649171
10000036   71567     1805     4.0  912649010
10000037   71567     1833     3.0  912649171
10000038   71567     1876     3.0  912580722
10000039   71567     1909     2.0  912580688
10000040   71567     1917     4.0  912580787
10000041   71567     1920     4.0  912578247
10000042   71567     1982     1.0  912580553
10000043   71567     1983     1.0  912580553
10000044   71567     1984     1.0  912580553
10000045   71567     1985     1.0  912580553
10000046   71567     1986     1.0  912580553
10000047   71567     2012     3.0  912580722
10000048   71567     2028     5.0  912580344
10000049   71567     2107     1.0  912580553
10000050   71567     2126     2.0  912649143
10000051   71567     2294     5.0  912577968
10000052   71567     2338     2.0  912578016
10000053   71567     2384     2.0  912578173

[10000054 rows x 4 columns]

In [12]:
movie_index = {k:v for (v,k) in movies.movieId.to_dict().items()}

In [17]:
movie_count = len(movies)
user_count = max(ratings.userId)

mean_score = ratings.rating.values.mean()

In [37]:
all_scores = np.zeros((user_count, movie_count))
for (user, movie, rating, _) in ratings.values:
    all_scores[int(user)-1, movie_index[int(movie)]] = rating
all_scores = all_scores[np.where(all_scores.sum(axis=1) > 0)[0]]

In [19]:
def train_test_split(scores, seed=1234, set_seed=True):
    N = scores.shape[0]
    test_size = N / 10
    if set_seed:
        np.random.seed(seed)
    test_idx = np.random.choice(N, test_size, replace=False)
    test_set = scores[test_idx]
    train_set = np.delete(scores, test_idx, axis=0)
    return train_set, test_set

def query_target_split(test_set, seed=1234, set_seed=True):
    query_set = test_set.copy()
    target_set = test_set.copy()
    if set_seed:
        np.random.seed(seed)
    for u in xrange(test_set.shape[0]):
        rated = np.where(test_set[u] > 0)[0]
        target = np.random.choice(rated, rated.size / 2, replace=False)
        query_set[u,target] = 0
    target_set[np.where(query_set > 0)] = 0
    return query_set, target_set

def evaluate_ratings(scores, target, method='nmae', min_rate=.5):
    mask = target > 0
    abs_dists = np.abs(scores * mask - target)
    if method == 'mae':
        return abs_dists.sum() / mask.sum()
    elif method == 'nmae':
        return abs_dists.sum() / mask.sum() / (5. - min_rate)
    elif method == 'rmse':
        return np.sqrt((abs_dists**2).sum() / mask.sum())
    else:
        raise Exception('Invalid argument value: method')
        
def compare_genres(userID, recoms):
    genres = {}
    for c in map(lambda x: get_info(x,'genres'), ratings.movieId.values[np.where(ratings.userId.values == userID)]):
        for g in c[0].split('|'):
            if g not in genres:
                genres[g] = 0
            genres[g] += 1
            
    recom_genres = {}
    for c in movies.genres.values[recoms[:100]]:
        for g in c.split('|'):
            if g not in recom_genres:
                recom_genres[g] = 0
            recom_genres[g] += 1
            
    return sorted(genres.items(), key=lambda x: x[1], reverse=True), \
           sorted(recom_genres.items(), key=lambda x: x[1], reverse=True)

In [20]:
def get_info(movieId, info='title'):
    return movies[info].values[np.where(movies.movieId.values == movieId)]

def get_user_ratings(userId):
    return ratings.values[np.where(ratings.userId == userId)][:,1:]

In [21]:
def user_baselines(train, query=None, mean_score=None):
    if query is None:
        query = train
    if mean_score is None:
        mean_score = train.sum() / np.count_nonzero(train)
    baselines = query.sum(axis=1) / (query > 0).sum(axis=1) - mean_score
    return np.nan_to_num(baselines)

def item_baselines(train, usr_baselines=None, mean_score=None):
    if mean_score is None:
        mean_score = train.sum() / np.count_nonzero(train)
    if usr_baselines is None:
        usr_baselines = user_baselines(train, mean_score=mean_score)
    nonzeros = (train > 0).sum(axis=0)
    usr_baselines = usr_baselines[:, np.newaxis] * (train > 0)
    preds = (train.sum(axis=0) - usr_baselines.sum(axis=0)) / nonzeros - mean_score
    return np.nan_to_num(preds)

# ta funkcja zwraca szacowania nawet istniejących ocen

def baseline_predictors(train, query=None, mean_score=None):
    if query is None:
        query = train
    if mean_score is None:
        mean_score = train.sum() / np.count_nonzero(train)
    usr_baselines = user_baselines(train, query, mean_score)
    itm_baselines = item_baselines(train, mean_score=mean_score)
    return mean_score + usr_baselines[:, np.newaxis] + itm_baselines

In [22]:
def per_user_means(scores):    
    return scores.sum(axis=1) / (scores > 0).sum(axis=1)

def per_user_stds(scores):
    means = per_user_means(scores)
    nonzeros = (scores > 0).sum(axis=1)
    sums = scores.sum(axis=1)
    sq_sums = (scores**2).sum(axis=1)
    return np.sqrt((sq_sums + nonzeros*means**2 - 2*means*sums) / nonzeros)

# user-user CF

In [23]:
def scores_cf_uu(train, query, target_inds, n, subtract_mean=True, div_by_std=True, metric='pearson'):
    assert not (div_by_std and not subtract_mean)
    
    ratings = []
    num_ratings = []
    
    train_rated = train > 0
    train_means = per_user_means(train)
    train_stds = per_user_stds(train)
    
    train_centered = (train - train_means[:, np.newaxis]) * train_rated
    
    query_means = per_user_means(query)
    query_stds = per_user_stds(query)
    
    baselines = baseline_predictors(train, query)
    
    for u_idx in xrange(query.shape[0]):

        user_ratings = query[u_idx]
        user_rated = user_ratings > 0
        user_mean = query_means[u_idx]
        user_std = query_stds[u_idx]
        user_baseline = baselines[u_idx]
        
        targets = np.where(target_inds[u_idx])[0]
        interesting_users_inds = np.unique(np.where(train_rated[:, targets])[0])
        train_cut = train_centered[interesting_users_inds]
        train_cut_rated = train_rated[interesting_users_inds]
        
        targets_ratings = train[interesting_users_inds][:, targets]
        
        user_centered = (user_ratings - user_mean) * user_rated

        if metric == 'cosine':
            dists = cdist(user_centered[np.newaxis], train_cut, metric='cosine')
        elif metric == 'pearson':
            numerator = user_centered.dot(train_cut.T)
            denom1 = (user_centered**2).dot(train_cut_rated.T)
            denom2 = user_rated.dot((train_cut**2).T)
            dists = (numerator / np.sqrt(denom1 * denom2))[np.newaxis]

        dists_zero_idx = np.where((dists == 0).T * train_cut_rated[:, targets])

        per_item_dists = dists.T * train_cut_rated[:, targets]
        per_item_dists[per_item_dists == 0] = np.nan
        per_item_dists[dists_zero_idx] = 0
        
        if per_item_dists.shape[0] > n:
            order = per_item_dists.argpartition(axis=0, kth=n-1)[:n]
        else:
            order = np.indices((per_item_dists.shape[0], targets.size))[0]
        
        weights = per_item_dists[order, np.arange(targets.size)]

        ratings_gathered = (~np.isnan(weights)).sum(axis=0)

        weights = np.nan_to_num(weights)
        
        scores = targets_ratings[order, np.arange(targets.size)]
        if subtract_mean:
            multiplier = train_stds[interesting_users_inds][order] if div_by_std else 1
            scores = (scores - train_means[interesting_users_inds][order]) / multiplier

        scores = (scores * weights).sum(axis=0) / (np.abs(weights)).sum(axis=0)
        
        estimated_ratings = np.zeros(query.shape[1])
        estimated_ratings[targets] = scores
        
        if subtract_mean:
            multiplier = user_std if div_by_std else 1.        
            estimated_ratings = user_mean + multiplier * estimated_ratings
            
        estimated_ratings[user_rated] = user_ratings[user_rated]

        # dla ocen nan dajemy baseline predictor

        estimated_ratings[np.isnan(estimated_ratings)] = user_baseline[np.isnan(estimated_ratings)]
        
        ratings.append(estimated_ratings[np.newaxis])
        
        user_num_ratings = np.zeros(query.shape[1])
        user_num_ratings[targets] = ratings_gathered
        num_ratings.append(user_num_ratings[np.newaxis])
        
    ratings = np.vstack(ratings)
    num_ratings = np.vstack(num_ratings)
        
    return ratings, num_ratings

In [24]:
def recommend_cf_uu(userId, n, scores, min_n=0, subtract_mean=True, div_by_std=True, metric='pearson'):
    
    estimated_ratings, ratings_gathered = scores_cf_uu(scores, scores[userId-1][np.newaxis], 
                                                       [np.ones(scores.shape[1])], n, subtract_mean, 
                                                       div_by_std, metric)
    estimated_ratings, ratings_gathered = estimated_ratings[0], ratings_gathered[0]
    estimated_ratings[scores[userId-1] > 0] = np.nan
    estimated_ratings[ratings_gathered < min_n] = np.nan
    
    movie_order = (-estimated_ratings).argsort()
    
    return movie_order + 1, estimated_ratings[movie_order], ratings_gathered[movie_order]

# item-item CF

In [25]:
def calculate_similarities_cf_ii(scores, nan_to_1=True):
    dists = cdist(scores.T, scores.T, metric='cosine')
    if nan_to_1:
        dists[np.isnan(dists)] = 1
    return dists

In [26]:
def scores_cf_ii(train, query, target_inds, n, dists=None):
    if dists is None:
        raise NotImplementedError('distances have to be precomputed')
    
    ratings = []
    
    baselines = baseline_predictors(train, query)
    
    for u_idx in xrange(query.shape[0]):

        user_ratings = query[u_idx]
        user_rated = user_ratings > 0
        user_baseline = baselines[u_idx]
        
        targets = np.where(target_inds[u_idx])[0]        

        user_dists = dists[targets][:, user_rated]
        if user_dists.shape[1] > n:
            order = user_dists.argpartition(axis=1, kth=n-1)[:, :n]
        else:
            order = np.indices((targets.size, user_dists.shape[1]))[1]
        weights = user_dists[np.arange(targets.size)[:, np.newaxis], order]

        scores = user_ratings[user_rated][order] - user_baseline[targets, np.newaxis]
        scores = (scores * weights).sum(axis=1) / (np.abs(weights)).sum(axis=1) + user_baseline[targets]
            
        estimated_ratings = np.zeros(query.shape[1])
        estimated_ratings[targets] = scores
        estimated_ratings[user_rated] = user_ratings[user_rated]
        
        ratings.append(estimated_ratings[np.newaxis])

    return np.vstack(ratings)

In [27]:
def recommend_cf_ii(userId, n, scores, dists=None):
    if dists is None:
        raise NotImplementedError('distances have to be precomputed')

    estimated_ratings = scores_cf_ii(scores, scores[userId-1][np.newaxis], [np.ones(scores.shape[1])], 
                                     n, dists=dists)[0]
    estimated_ratings[scores[userId-1] > 0] = np.nan
    
    movie_order = (-estimated_ratings).argsort()
    
    return movie_order + 1, estimated_ratings[movie_order]

# Slope One

# basic

In [28]:
def calculate_similarities_SO(scores, nan_to_0=True):
    rated = scores > 0
    dists = scores.T.dot(rated)
    dists = dists - dists.T
    cards = rated.T.dot(rated.astype(np.float))
    return np.nan_to_num(dists / cards), cards

In [29]:
def scores_SO_basic(train, query, target_inds, dists=None):
    if dists is None:
        raise NotImplementedError('distances have to be precomputed')
        
    ratings = []    
        
    for u_idx in xrange(query.shape[0]):
        user_ratings = query[u_idx]
        user_rated = user_ratings > 0
        
        targets = np.where(target_inds[u_idx])[0]        

        user_mean = user_ratings.sum() / user_rated.sum()
        scores = dists[targets][:, user_rated].mean(axis=1) + user_mean
        
        estimated_ratings = np.zeros(query.shape[1])
        estimated_ratings[targets] = scores
        estimated_ratings[user_rated] = user_ratings[user_rated]
        
        ratings.append(estimated_ratings[np.newaxis])
        
    return np.vstack(ratings)

In [30]:
def recommend_SO_basic(userId, scores, dists=None):
    if dists is None:
        raise NotImplementedError('distances have to be precomputed')

    estimated_ratings = scores_SO_basic(scores, scores[userId-1][np.newaxis], [np.ones(scores.shape[1])], dists)[0]
    estimated_ratings[scores[userId-1] > 0] = np.nan
    
    movie_order = (-estimated_ratings).argsort()
    
    return movie_order + 1, estimated_ratings[movie_order]

# weighted

In [31]:
def scores_SO_weighted(train, query, target_inds, dists_cards=None):
    if dists_cards is None:
        raise NotImplementedError('distances and cardinalities have to be precomputed')
        
    dists, cards = dists_cards
        
    ratings = []    
        
    for u_idx in xrange(query.shape[0]):
        user_ratings = query[u_idx]
        user_rated = user_ratings > 0
        
        targets = np.where(target_inds[u_idx])[0]        
        
        weights = cards[targets][:, user_rated]
        scores = dists[targets][:, user_rated] + user_ratings[user_rated]
        scores = (scores * weights).sum(axis=1) / weights.sum(axis=1)
        
        estimated_ratings = np.zeros(query.shape[1])
        estimated_ratings[targets] = scores
        estimated_ratings[user_rated] = user_ratings[user_rated]
        
        ratings.append(estimated_ratings[np.newaxis])
        
    return np.vstack(ratings)

# bi-polar

In [32]:
def calculate_similarities_SO_bipolar(scores, nan_to_0=True):
    means = per_user_means(scores)[:, np.newaxis]
    liked = scores >= means
    disliked = (scores < means) * (scores > 0)
    
    def calculate_dists(mask):
        dists = (scores * mask).T.dot(mask)
        dists = dists - dists.T
        cards = mask.T.dot(mask.astype(np.float))
        return np.nan_to_num(dists / cards), cards
    
    dists_like = calculate_dists(liked)
    dists_dislike = calculate_dists(disliked)
    
    return dists_like, dists_dislike

In [33]:
def scores_SO_bipolar(train, query, target_inds, dists_cards_liked=None, dists_cards_disliked=None):
    if dists_cards_liked is None or dists_cards_disliked is None:
        raise NotImplementedError('distances and cardinalities have to be precomputed')
        
    dists_l, cards_l = dists_cards_liked
    dists_d, cards_d = dists_cards_disliked
        
    ratings = []    
        
    for u_idx in xrange(query.shape[0]):
        user_ratings = query[u_idx]
        user_rated = user_ratings > 0
        user_mean = user_ratings.sum() / user_rated.sum()
        
        user_l = user_ratings >= user_mean
        user_d = (user_ratings < user_mean) * (user_ratings > 0)
        
        targets = np.where(target_inds[u_idx])[0]        
        
        weights_l = cards_l[targets][:, user_l]
        weights_d = cards_d[targets][:, user_d]
        
        scores_l = ((dists[targets][:, user_l] + user_ratings[user_l]) * weights_l).sum(axis=1)
        scores_d = ((dists[targets][:, user_d] + user_ratings[user_d]) * weights_d).sum(axis=1)
        
        scores = (scores_l + scores_d) / (weights_l.sum(axis=1) + weights_d.sum(axis=1))
        
        estimated_ratings = np.zeros(query.shape[1])
        estimated_ratings[targets] = scores
        estimated_ratings[user_rated] = user_ratings[user_rated]
        
        ratings.append(estimated_ratings[np.newaxis])
        
    return np.vstack(ratings)

# testy

In [44]:
seed = np.random.randint(1, 1000000)
seed = 12340
train, test = train_test_split(all_scores, seed)
query, target = query_target_split(test, seed, True)

# baseline evaluation

In [45]:
evaluate_ratings(baseline_predictors(train, query), target, method='mae')

0.68164734144577122

# testy uu

In [246]:
userId = 55

t0 = time.time()
recoms, scores, sample_size = recommend_cf_uu(userId, 50, all_scores, 10, metric='cosine')
print time.time()-t0
scores[:10], recoms[:10]

1.6916987896


(array([ 4.93597315,  4.82404485,  4.81861098,  4.76318241,  4.76081769,
         4.75777036,  4.75484343,  4.75229947,  4.73198646,  4.73163966]),
 array([2837, 3270, 1221,  942, 2962, 1181,  258, 1133, 2129, 1243]))

In [62]:
t0 = time.time()
S = scores_cf_uu(train, query, target > 0, 50, metric='cosine')[0]
time.time() - t0

MemoryError: 

In [ ]:
evaluate_ratings(S, target, method='mae')

# testy ii

In [249]:
dists = calculate_similarities_cf_ii(all_scores)

In [250]:
userId = 55

t0 = time.time()
recoms, scores = recommend_cf_ii(userId, 50, all_scores, dists=dists)
print time.time()-t0
scores[:10], recoms[:10]

0.279159069061


(array([ 4.14650447,  4.14532208,  4.14211497,  4.14203507,  4.14176689,
         4.14122667,  4.14080789,  4.14073863,  4.14069204,  4.14055616]),
 array([2951,  161, 1132, 3204, 3673, 1080,  532, 1210, 1175, 1173]))

In [46]:
dists = calculate_similarities_cf_ii(train)

In [47]:
t0 = time.time()
S_ii = scores_cf_ii(train, query, target > 0, 40, dists)
time.time() - t0

17.264770030975342

In [48]:
evaluate_ratings(S_ii, target, method='mae')

0.70963052876509469

# testy SO basic

In [49]:
dists = calculate_similarities_SO(all_scores)[0]

In [51]:
userId = 55

t0 = time.time()
recoms, scores = recommend_SO_basic(userId, all_scores, dists=dists)
print time.time()-t0
scores[:10], recoms[:10]

0.191313028336


(array([ 4.67724868,  4.5625    ,  4.22222222,  4.21385666,  4.1912037 ,
         4.17361111,  4.16187209,  4.15883114,  4.14116622,  4.13657407]),
 array([ 9032,  9084,  9409,  9391, 10676,  8406,   316,  6558,    50,  9009]))

In [52]:
dists = calculate_similarities_SO(train)[0]

In [53]:
t0 = time.time()
S = scores_SO_basic(train, query, target > 0, dists)
time.time() - t0

8.177078008651733

In [54]:
evaluate_ratings(np.nan_to_num(S), target, method='mae')

0.66299560571636929

# testy SO weighted

In [55]:
dists_cards = calculate_similarities_SO(train)

In [57]:
t0 = time.time()
S = scores_SO_weighted(train, query, target > 0, dists_cards)
time.time() - t0

15.70959186553955

In [58]:
evaluate_ratings(np.nan_to_num(S), target, method='mae')

0.6612443237782728

# testy SO bi-polar

In [59]:
dists_cards_l, dists_cards_d = calculate_similarities_SO_bipolar(train)

In [60]:
t0 = time.time()
S = scores_SO_bipolar(train, query, target > 0, dists_cards_l, dists_cards_d)
time.time() - t0

28.759602069854736

In [61]:
evaluate_ratings(np.nan_to_num(S), target, method='mae')

0.66863814018315582