In [1]:
import numpy as np
import pandas as pd
from scipy.spatial.distance import cdist
from scipy.sparse import csr_matrix, lil_matrix
import time

In [2]:
def read_small():
    data_path = 'ml-latest-small/'
    movies = pd.read_csv(data_path + 'movies.csv')
    ratings = pd.read_csv(data_path + 'ratings.csv')
    return movies, ratings

def read_10M():
    data_path = 'ml-10M100K/'
    movies = pd.read_csv(data_path + 'movies.dat', delimiter='::', engine='python')
    ratings = pd.read_csv(data_path + 'ratings.dat', delimiter='::', engine='python')
    return movies, ratings

In [3]:
movies, ratings = read_small()

In [4]:
movies

movieId                                              title  \
0           1                                   Toy Story (1995)   
1           2                                     Jumanji (1995)   
2           3                            Grumpier Old Men (1995)   
3           4                           Waiting to Exhale (1995)   
4           5                 Father of the Bride Part II (1995)   
5           6                                        Heat (1995)   
6           7                                     Sabrina (1995)   
7           8                                Tom and Huck (1995)   
8           9                                Sudden Death (1995)   
9          10                                   GoldenEye (1995)   
10         11                     American President, The (1995)   
11         12                 Dracula: Dead and Loving It (1995)   
12         13                                       Balto (1995)   
13         14                                       Nixon (1995)   
14         15                            Cutthroat Island (1995)   
15         16                                      Casino (1995)   
16         17                       Sense and Sensibility (1995)   
17         18                                  Four Rooms (1995)   
18         19              Ace Ventura: When Nature Calls (1995)   
19         20                                 Money Train (1995)   
20         21                                  Get Shorty (1995)   
21         22                                     Copycat (1995)   
22         23                                   Assassins (1995)   
23         24                                      Powder (1995)   
24         25                           Leaving Las Vegas (1995)   
25         26                                     Othello (1995)   
26         27                                Now and Then (1995)   
27         28                                  Persuasion (1995)   
28         29  City of Lost Children, The (Cité des enfants p...   
29         30  Shanghai Triad (Yao a yao yao dao waipo qiao) ...   
...       ...                                                ...   
9095   159690  Teenage Mutant Ninja Turtles: Out of the Shado...   
9096   159755          Popstar: Never Stop Never Stopping (2016)   
9097   159858                             The Conjuring 2 (2016)   
9098   159972                     Approaching the Unknown (2016)   
9099   160080                                Ghostbusters (2016)   
9100   160271                        Central Intelligence (2016)   
9101   160438                                Jason Bourne (2016)   
9102   160440                             The Maid's Room (2014)   
9103   160563                        The Legend of Tarzan (2016)   
9104   160565                    The Purge: Election Year (2016)   
9105   160567              Mike & Dave Need Wedding Dates (2016)   
9106   160590                         Survive and Advance (2013)   
9107   160656                                    Tallulah (2016)   
9108   160718                                       Piper (2016)   
9109   160954                                       Nerve (2016)   
9110   161084                       My Friend Rockefeller (2015)   
9111   161155                                   Sunspring (2016)   
9112   161336                  Author: The JT LeRoy Story (2016)   
9113   161582                          Hell or High Water (2016)   
9114   161594               Kingsglaive: Final Fantasy XV (2016)   
9115   161830                                        Body (2015)   
9116   161918                Sharknado 4: The 4th Awakens (2016)   
9117   161944              The Last Brickmaker in America (2001)   
9118   162376                                    Stranger Things   
9119   162542                                      Rustom (2016)   
9120   162672                                Mohenjo Daro (2016)   
9121   163056                               Shin Godzilla (201

In [5]:
ratings

userId  movieId  rating   timestamp
0            1       31     2.5  1260759144
1            1     1029     3.0  1260759179
2            1     1061     3.0  1260759182
3            1     1129     2.0  1260759185
4            1     1172     4.0  1260759205
5            1     1263     2.0  1260759151
6            1     1287     2.0  1260759187
7            1     1293     2.0  1260759148
8            1     1339     3.5  1260759125
9            1     1343     2.0  1260759131
10           1     1371     2.5  1260759135
11           1     1405     1.0  1260759203
12           1     1953     4.0  1260759191
13           1     2105     4.0  1260759139
14           1     2150     3.0  1260759194
15           1     2193     2.0  1260759198
16           1     2294     2.0  1260759108
17           1     2455     2.5  1260759113
18           1     2968     1.0  1260759200
19           1     3671     3.0  1260759117
20           2       10     4.0   835355493
21           2       17     5.0   835355681
22           2       39     5.0   835355604
23           2       47     4.0   835355552
24           2       50     4.0   835355586
25           2       52     3.0   835356031
26           2       62     3.0   835355749
27           2      110     4.0   835355532
28           2      144     3.0   835356016
29           2      150     5.0   835355395
...        ...      ...     ...         ...
99974      671     4034     4.5  1064245493
99975      671     4306     5.0  1064245548
99976      671     4308     3.5  1065111985
99977      671     4880     4.0  1065111973
99978      671     4886     5.0  1064245488
99979      671     4896     5.0  1065111996
99980      671     4963     4.5  1065111855
99981      671     4973     4.5  1064245471
99982      671     4993     5.0  1064245483
99983      671     4995     4.0  1064891537
99984      671     5010     2.0  1066793004
99985      671     5218     2.0  1065111990
99986      671     5299     3.0  1065112004
99987      671     5349     4.0  1065111863
99988      671     5377     4.0  1064245557
99989      671     5445     4.5  1064891627
99990      671     5464     3.0  1064891549
99991      671     5669     4.0  1063502711
99992      671     5816     4.0  1065111963
99993      671     5902     3.5  1064245507
99994      671     5952     5.0  1063502716
99995      671     5989     4.0  1064890625
99996      671     5991     4.5  1064245387
99997      671     5995     4.0  1066793014
99998      671     6212     2.5  1065149436
99999      671     6268     2.5  1065579370
100000     671     6269     4.0  1065149201
100001     671     6365     4.0  1070940363
100002     671     6385     2.5  1070979663
100003     671     6565     3.5  1074784724

[100004 rows x 4 columns]

In [6]:
movie_count = len(movies)
user_count = max(ratings.userId)

mean_score = ratings.rating.values.mean()

In [7]:
all_scores = np.zeros((user_count, max(movies.movieId)), dtype=np.float32)
for (user, movie, rating, _) in ratings.values:
    all_scores[int(user)-1,int(movie)-1] = rating
all_scores = all_scores[:,movies.movieId.values.astype(int)-1]

In [8]:
def get_info(movieId, info='title'):
    return movies[info].values[np.where(movies.movieId.values == movieId)]

In [9]:
def get_user_ratings(userId):
    return ratings.values[np.where(ratings.userId == userId)][:,1:]

In [10]:
def user_baselines():
    all_scores_local = all_scores.copy()
    all_scores_local[all_scores_local == 0] = np.nan
    all_scores_local -= mean_score
    means = np.nanmean(all_scores_local, axis=1)
    return np.nan_to_num(means)

In [11]:
def item_baselines():
    usr_baselines = user_baselines()[:, np.newaxis]
    all_scores_local = all_scores.copy()
    all_scores_local[all_scores_local == 0] = np.nan
    all_scores_local -= usr_baselines + mean_score
    means = np.nanmean(all_scores_local, axis=0)
    return np.nan_to_num(means)

In [12]:
# ta funkcja zwraca szacowania nawet istniejących ocen

def baseline_predictors():
    usr_baselines = user_baselines()[:, np.newaxis]
    itm_baselines = item_baselines()
    scores = np.ones((user_count, movie_count)) * mean_score
    return scores + usr_baselines + itm_baselines

In [13]:
def recommend_cf_uu(userId, n, min_n=0, subtract_mean=True, div_by_std=True, weighted=True, metric='pearson'):
    assert not (div_by_std and not subtract_mean)
    all_scores_local = all_scores.copy()
    
    all_rated = all_scores_local > 0    
    user_rated = all_rated[userId]
    
    all_scores_local[all_scores_local == 0] = np.nan
    
    means = np.nanmean(all_scores_local, axis=1)
    user_mean = means[userId-1]
        
    stds = np.nanstd(all_scores_local, axis=1)
    user_std = stds[userId-1]
        
    all_scores_local = np.nan_to_num(all_scores_local)
    
    user_ratings = all_scores_local[userId-1]
    
    t0 = time.time()
    
    if metric == 'cosine':
        dists = cdist(user_ratings[np.newaxis] - user_mean, all_scores_local - means[:, np.newaxis], 
                      metric='cosine')[0]
    elif metric == 'pearson':
        user_centered = (user_ratings - user_mean) * user_rated
        all_centered = (all_scores_local - means[:, np.newaxis]) * all_rated
        numerator = (user_centered * all_centered).sum(axis=1)
        denominator = np.sqrt((user_centered**2).sum()) * np.sqrt((all_centered**2).sum(axis=1))
        dists = numerator / denominator
    
    print time.time()-t0
    
    order = dists.argsort()
    order = np.delete(order, np.where(order == userId-1))
    estimated_ratings = np.zeros(movie_count)
    ratings_gathered = np.zeros(movie_count, dtype=np.int8)
    denominators = np.zeros(movie_count)
    
    t0 = time.time()
    
    i = 0
    for u in order:
        mask = all_rated[u] * (ratings_gathered < n)
        weight = (1 - dists[u]) if weighted else 1.
        mean = means[u] if subtract_mean else 0.
        std = stds[u] if div_by_std else 1.
        estimated_ratings += (all_scores_local[u] - mean) / std * mask * weight
        ratings_gathered += mask
        denominators += np.abs(mask * weight)
        if all(ratings_gathered == n):
            break
        i += 1
            
    print time.time()-t0
                
    estimated_ratings /= denominators
    estimated_ratings[ratings_gathered < min_n] = np.nan
    estimated_ratings[user_rated] = np.nan
    
    if subtract_mean:
        multiplier = user_std if div_by_std else 1.        
        estimated_ratings = user_mean + multiplier * estimated_ratings
    
    movie_order = (-estimated_ratings).argsort()
    
    return movie_order + 1, estimated_ratings[movie_order], ratings_gathered[movie_order]

In [14]:
def calculate_similarities_cf_ii():
    return cdist(all_scores.T, all_scores.T, metric='cosine')

In [90]:
def recommend_cf_ii(userId, n, dists=None):
    if dists is None:
        raise NotImplementedError('distances have to be precomputed')

    user_scores = all_scores[userId]
    user_rated = user_scores > 0

    dists = dists[:, user_rated]
    if dists.shape[1] > n:
        order = dists.argpartition(axis=1, kth=n-1)[:, :n]
    else:
        order = np.indices((movie_count, dists.shape[1]))[1]
    weights = dists[np.arange(movie_count)[:, np.newaxis], order]
    
    base_user_preds = baseline_predictors()[userId]
    estimated_ratings = user_scores[user_rated][order] - base_user_preds[:, np.newaxis]
    estimated_ratings = (estimated_ratings * weights).sum(axis=1) / \
                        (np.abs(weights)).sum(axis=1) + base_user_preds
    estimated_ratings[user_rated] = np.nan
    
    movie_order = (-estimated_ratings).argsort()
    
    return movie_order + 1, estimated_ratings[movie_order]

In [16]:
def compare_genres(userID, recoms):
    genres = {}
    for c in map(lambda x: get_info(x,'genres'), ratings.movieId.values[np.where(ratings.userId.values == userID)]):
        for g in c[0].split('|'):
            if g not in genres:
                genres[g] = 0
            genres[g] += 1
            
    recom_genres = {}
    for c in movies.genres.values[recoms[:100]]:
        for g in c.split('|'):
            if g not in recom_genres:
                recom_genres[g] = 0
            recom_genres[g] += 1
            
    return sorted(genres.items(), key=lambda x: x[1], reverse=True), \
           sorted(recom_genres.items(), key=lambda x: x[1], reverse=True)

# testy uu

In [17]:
userId = 5

In [18]:
recoms, scores, sample_size = recommend_cf_uu(userId, 50, 10, subtract_mean=True, div_by_std=True, 
                                              weighted=True, metric='pearson')
scores[:10], sample_size[:10]

0.028088092804
0.063728094101


(array([ 4.57353462,  4.52208989,  4.43930143,  4.40418622,  4.40411773,
         4.40350698,  4.40028808,  4.39415057,  4.3912664 ,  4.38195306]),
 array([11, 50, 11, 22, 50, 50, 50, 12, 50, 50], dtype=int8))

In [19]:
genres, recom_genres = compare_genres(userId, recoms)
print genres
print ''
print recom_genres

[('Comedy', 55), ('Drama', 39), ('Romance', 37), ('Adventure', 20), ('Children', 14), ('Fantasy', 14), ('Action', 12), ('Thriller', 12), ('Musical', 10), ('Animation', 10), ('Crime', 10), ('Sci-Fi', 7), ('Mystery', 6), ('IMAX', 5), ('Horror', 4), ('War', 4), ('Documentary', 3)]

[('Drama', 58), ('Comedy', 40), ('Romance', 25), ('Thriller', 18), ('Action', 15), ('Adventure', 14), ('Crime', 13), ('Sci-Fi', 11), ('Mystery', 8), ('Fantasy', 8), ('Horror', 7), ('Musical', 5), ('War', 5), ('Film-Noir', 3), ('Animation', 3), ('Children', 3), ('Documentary', 1), ('Western', 1)]


# testy ii

In [20]:
dists = calculate_similarities_cf_ii()

In [64]:
userId = 50

In [96]:
t0 = time.time()
recoms, scores = recommend_cf_ii(userId, 50, dists=dists)
print time.time()-t0
scores[:10]

0.224896907806


array([ 4.04451237,  4.04451237,  4.04451237,  4.04451237,  4.04451237,
        4.04451237,  4.04451237,  4.04451237,  4.03757788,  4.0256001 ])

In [79]:
np.indices((3,4))[1]

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])